---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xiu.
--- DateTime: 2023/2/8 20:00
---
---argv[1]是优惠券id
---argv[2]是用户id
local stockKey="seckill:stock:" .. ARGV[1]
local userid=ARGV[2]
local stockOrderKey="seckill:order:" .. ARGV[1]
--判断库存是否充足，不充足返回1
if (tonumber( redis.call('get',stockKey))<=0) then
    return 1
end
--判断用户是否已经下单
if redis.call('sismember',stockOrderKey,userid) ==1 then
    return 2
end
redis.call('incrby',stockKey,-1)
redis.call('sadd',stockOrderKey,userid)
return 0